"""transactions-update

Revision ID: cd26f16637e5
Revises: 5c1cb5ede26b
Create Date: 2024-06-25 11:00:11.026496

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd26f16637e5'
down_revision = '5c1cb5ede26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', mysql.ENUM('Applied', 'Scheduled', 'Canceled'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
