"""core-models

Revision ID: 28d0af639e24
Revises: fb50b9cca5b7
Create Date: 2024-07-11 11:45:05.636481

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '28d0af639e24'
down_revision = 'fb50b9cca5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
