"""core-models

Revision ID: fb50b9cca5b7
Revises: 4dd43a514f08
Create Date: 2024-07-11 11:41:21.654205

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fb50b9cca5b7'
down_revision = '4dd43a514f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('safe', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'safe')
    # ### end Alembic commands ###
